name: CI
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install backend
        working-directory: backend
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -e '.[dev]'
      - name: Lint (ruff)
        working-directory: backend
        run: |
          source .venv/bin/activate
          pip install ruff
          ruff check app
      - name: Tests
        env:
          DETERMINISTIC_TESTS: "1"
        working-directory: backend
        run: |
          source .venv/bin/activate
          pytest -q
